<?php
header("Content-Type: application/json");

$response = array(
    'message' => 'this message was generated by php, hello from bpj',
    'heading' => 'Hello php',
    'IP' => $_SERVER['REMOTE_ADDR'],
    'title' => 'Hello php',
    'time' => strftime('%c')
);


echo json_encode($response);
?>
